[package]
name = "trussed-rsa-backend"
version = "0.1.0"
edition = "2021"
description = "Trussed backend adding support for the RSA algorithm using an allocator"
authors = ["Nitrokey GmbH <info@nitrokey.com>"]
license = "LGPL-3.0-only"
rust-version = "1.66"
keywords = ["trussed", "rsa", "no-std"]

[dependencies]
delog = "0.1.6"
heapless-bytes = "0.3.0"
num-bigint-dig = { version = "0.8.2", default-features = false }
rsa = { version = "0.8.1", default-features = false, features = ["sha2"]}
serde = { version = "1.0.152", default-features = false, features = ["derive"] }

trussed = { git = "https://github.com/trussed-dev/trussed.git", rev = "effa378c4709a2ec6119673894ed68a18d8e7391" }

[dev-dependencies]
hex-literal = "0.3.4"

delog = { version = "0.1.6", features = ["std-log"] }
test-log = "0.2.11"
env_logger = "0.10.0"
rand = "0.8.5"

[features]

default = []
virt = ["std","trussed/virt"]
std = []

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []

[profile.dev.package.rsa]
opt-level = 2

[profile.dev.package.num-bigint-dig]
opt-level = 2
